name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Build (dev)
      if: github.ref == 'refs/heads/dev'
      run: go build -v ./...

    - name: Test (main)
      if: github.ref == 'refs/heads/main'
      run: go test -v ./...
